api_version = "2026-04"
uid = "481f0e81-a8fa-e1ba-936c-c5839f1dcf13881b2d0d"

[[extensions]]
name = "Asva AI agentic-readiness blocks"
handle = "asva-ai-tae"
type = "theme"

[extensions.capabilities]
block_progress = true
